dist: xenial
language: python
python:
  - '3.7'
stages:
  - build
  - static-checks
  - test
jobs:
  include:
    - stage: build
      script:
        - python setup.py install
    - stage: static-checks
      script:
        - echo "Nothing to do yet."
    - stage: test
      script:  # coverage
        - coverage run -m unittest
        - coverage report
        - codecov
